export KUBERNETES_SERVICE_HOST=HOSTIP
export KUBERNETES_SERVICE_PORT=6443
export KUBECONFIG=$HOME/.kube/config

export REMOTE_IP=${KUBERNETES_SERVICE_HOST}
export FISSION_URL=${REMOTE_IP}:PORT
export FISSION_ROUTER=${REMOTE_IP}:PORT
export FISSION_NAMESPACE=fission
